### ISSUE TITLE
Skyflash for Skywire mainnet

### ISSUE THREAD

**Issue by vidya88** [SkycoinProject/skyflash#4]
@olemis commented on Mar 5

Skywire mainnet released . Image and tool need updates to cope with that .

Additional context
[Official announcement](https://twitter.com/Skycoinproject/status/1102542728934637568) .

**Comment by jdknives** [comment]
Skyflash needs to be adapted to the mainnet as the mainnet requires the that the PubKey of the Hypervisor is passed to the config of the Visor so that it automatically connects and the user does not need to manually set that. There should be a field for the hypervisor PubKey in Skyflash therefore.

**Comment by jdknives** [comment]
Finished with https://github.com/SkycoinProject/skywire-mainnet/issues/245
